<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup Condition="'$(BuilderBundlePath)' != ''">
    <EmbeddedResource Include="$(BuilderBundlePath)" LogicalName="MKVDCU.BuilderBundle.zip" />
  </ItemGroup>
  <ItemGroup Condition="'$(UpdaterBinaryPath)' != ''">
    <EmbeddedResource Include="$(UpdaterBinaryPath)" LogicalName="MKVDCU.Updater.exe" />
  </ItemGroup>
  <ItemGroup Condition="'$(ReleaseManifestPath)' != ''">
    <EmbeddedResource Include="$(ReleaseManifestPath)" LogicalName="MKVDCU.ReleaseManifest.json" />
  </ItemGroup>

</Project>
